[build]
  publish = "."
  command = "echo 'No build required for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/qr1"
  to = "https://aiskillshouse.com/student/qr-mediator?uid=7697&promptId=22"
  status = 301

[[redirects]]
  from = "/qr2"
  to = "https://aiskillshouse.com/student/qr-mediator?uid=7697&promptId=21"
  status = 301

[[redirects]]
  from = "/qr3"
  to = "https://aiskillshouse.com/student/qr-mediator?uid=7697&promptId=20"
  status = 301

[[redirects]]
  from = "/qr4"
  to = "https://aiskillshouse.com/student/qr-mediator?uid=7697&promptId=19"
  status = 301

[[redirects]]
  from = "/qr5"
  to = "https://aiskillshouse.com/student/qr-mediator?uid=7697&promptId=18"
  status = 301